minVersion: 1.2.0
changelog: CHANGELOG.md
changelogPolicy: auto
preReleaseCommand: bash scripts/craft-pre-release.sh
github:
  owner: getsentry
  repo: conduit-client
artifactProvider:
  name: github
targets:
  - name: npm
